### ISSUE TITLE
Refactor `jwt` to be consistent with #143

### ISSUE THREAD

**Issue by KendallWeihe** [TBD54566975/web5-rs#144]
#143 proposes a new design for the `jws` crate; basically, we'll want to do the same with the `jwt` crate as the two are semantically mostly similar

So the new `jwt` design would be something like this:

```rust
use dids::{bearer::BearerDid, document::KeySelector};
use jws::v2::Header;
use serde::Serialize;

pub enum Error {
    // error cases
}

pub trait Claims: Serialize {}

pub struct BaseClaims {
    // all of the existing claims
}

pub struct Decoded<T: Claims> {
    pub header: Header,
    pub claims: T,
    pub signature: String,
    pub parts: Vec<String>,
}

pub struct Jwt;

impl Jwt {
    pub fn sign<T: Claims>(
        bearer_did: &BearerDid,
        key_selector: &KeySelector,
        header: Option<Header>,
        claims: &T,
    ) -> Result<String, Error> {
        unimplemented!()
    }

    pub fn decode<T: Claims>(compact_jws: &str) -> Result<Decoded<T>, Error> {
        unimplemented!()
    }

    pub fn verify<T: Claims>(compact_jws: &str) -> Result<Decoded<T>, JwtError> {
        unimplemented!()
    }
}
```

As with #143, this will break `credentials` and perhaps other things, so we should be conscious about the way the work is split up and reviewable

**Comment by KendallWeihe** [comment]
I'm actually not 100% about this bit, need to consider the VC dependency on JWT as a way to consider the ideal pattern.

```rust
pub trait Claims {
    fn encode(&self) -> String;
}
```

The idea being, we want a way for consuming projects (i.e. `credentials` crate) to be able to extend the `BaseClaims` to add. Also, we don't need to over engineer this; if the possible set of claims for all of our use cases is well known then we can just define all of the possible claims in the `jwt` crate itself, no need to get fancy if it's not required.

**Comment by KendallWeihe** [comment]
Ah okay, so now I recall why we can't just stuff everything at the `jwt` layer -- it's because of dependency design. The `VerifiableCredential` type is defined in the `credentials` package so we would have either duplicate definitions, circular dependencies, or the `VerifiableCredential` would counterintuitively not be in the `credentials` crate but would instead be in the `jwt` crate. Another solution is to move the JWT and JWS functionality to be within the `credentials` crate, but that would couple the two tightly together which feels off; for example, tbdex needs to create detached compact JWS for it's signatures, and to do that it would depend on the credentials crate. Alright so yeah I'm more inclined to use generics here.

But instead of what is in the OP, all we need is 

```rust
pub trait Claims: Serialize {}
```

We only need a `Claims` implementation to be json serializable. I've edited the OP accordingly.

**Comment by KendallWeihe** [comment]
For `sign()` we'll need to account for JWS Header overrides, for example in the KCC flow we use a custom header `typ`, so rather than this function signature:

```rust
    pub fn sign<T: Claims>(
        bearer_did: &BearerDid,
        key_selector: &KeySelector,
        claims: &T,
    ) -> Result<String, Error> {
        unimplemented!()
    }
```

We'll want to do something like this instead:

```rust
    pub fn sign<T: Claims>(
        bearer_did: &BearerDid,
        key_selector: &KeySelector,
        header: Option<Header>,
        claims: &T,
    ) -> Result<String, Error> {
        unimplemented!()
    }
```

Which, will use the provided `header` is it's `Some` else create the default header. Update OP accordingly.

**Comment by decentralgabe** [comment]
sounds reasonable to me.

**Comment by KendallWeihe** [comment]
Picking this work up, I'm making it a point to design our approach here to be conducive to future support for JWT's as JWE's, and not just JWS's (although we only currently need support for JWS). The only overlap between the two implementations (JWS & JWE) are the JWT claims, everything else is concretely different (same operations of sign/verify/decode but different input/output data structures). 

So the question is, how do we design the API surface here?
1. Two different struct implementations, `JwtAsJwe`/`JwtAsJws` (yuck, IMO)
2. One struct with differently named functions `Jwt::sign_jws()`/`Jwt::sign_jwe()`/etc (better IMO)
3. Two different struct implementations, both named `Jwt` but namespaced under different rust modules (`jwt::jws::Jwt`/`jwt::jwe::Jwt`) (best IMO)

I'm moving forward with (3) but open to hearing the case for (1) or (2)

**Comment by KendallWeihe** [comment]
And now I'm realizing JWE and JWS both have overlap in that they both use the same JOSE Header, created https://github.com/TBD54566975/web5-rs/issues/171 to discuss combining everything (minus JWK) into one crate
