### ISSUE TITLE
Use #144 in `credentials/vc.rs`

### ISSUE THREAD

**Issue by KendallWeihe** [TBD54566975/web5-rs#150]
Given we rework `jwt` in accordance with #144 and `jws` in accordance with #143 then we'll need to update `vc.rs` to use the latest.

A few items come to mind, but the work may span beyond this:
- `JwsHeader::from_bearer_did` will no longer exist (given we remove in in accordance with the commentary [linked here](https://github.com/TBD54566975/web5-rs/issues/143#issuecomment-2093593691))
- we can use `None` for the `header` param in `Jwt::sign()` as the default is acceptable
- no need to encode the claims, as that will happen internal to `Jwt::sign()`

**Comment by KendallWeihe** [comment]
Picking up this work and some things are coming to mind:

- we should probably codify the differentiation between VC Data Model 1.1 and 2.0
- are there differences in the ways we should implement the JWT across data models?

**Comment by KendallWeihe** [comment]
@decentralgabe could you answer or direct me to resources to answer this question?

> are there differences in the ways we should implement the JWT across data models?

**Comment by KendallWeihe** [comment]
I created a new ticket for the two above comments https://github.com/TBD54566975/web5-rs/issues/175

@decentralgabe please use the new ticket for discussions on the matter

**Comment by decentralgabe** [comment]
I will respond in 175 as well, but yes there is a difference between 1.1 and 2.0

1.1 follows unfortunate mapping rules defined here https://www.w3.org/TR/vc-data-model/#jwt-encoding

2.0 follows standards jwt conventions
