### ISSUE TITLE
Add `core` to artifact name for `binded/` projects

### ISSUE THREAD

**Issue by KendallWeihe** [TBD54566975/web5-rs#170]
We need to distinguish between [the actual `web5-kt` project](https://github.com/TBD54566975/web5-kt/) (where the idiomatic and expressive Kotlin code exists) and the binded `web5-kt-core` project (where the verbose and non-expressive UniFFI code-generated code exists); these are different projects. I propose we distinguish between the two by including the word `core` in the `binded/` project.

I'm referring to Kotlin as an example to prove the case, but this proposal spans to all projects within `binded/`

**Comment by KendallWeihe** [comment]
this was done for kt in #192

**Comment by nitro-neal** [comment]
This is done in tbdex-rs too
