### ISSUE TITLE
Remove the requirement of any peer dependencies

### ISSUE THREAD

**Issue by KendallWeihe** [TBD54566975/web5-rs#215]
We don't want developers to have to add multiple crate dependencies in order to use one feature, because then developers must concern themselves with determining compatible versions. Instead we want developers to be able to simply, for example, "add the `credentials` crate to your dependency and now you have everything you need."

This will impact our current API surface in a massive way, because effectively anywhere where we have a struct or function signature which includes a struct from a transitive dependency we'll have to augment. The easy solution would be to re-export transitive dependencies where appropriate (basically, the developer would still use the transitive dependency but at least it would be self-contained within the desired dependency such that version compatibility is managed at our layer), but relying on rust primitive types is preferred unless it's considered to be unwieldy.

**Comment by KendallWeihe** [comment]
How are we doing this in other SDKs?

**Comment by KendallWeihe** [comment]
@nitro-neal brought this up: what happens in the situation where developers actually need the transitive dependency for some other reason, but the versions aren't matched?

So their dependencies would look something like

- `credentials = "1.0.0"`
    - `dids = "1.0.0"` (this is transitive!)
- `dids = "2.0.0" (they need this for some other reason)

How would this work in rust lang?

**Comment by enmand** [comment]
> The easy solution would be to re-export transitive dependencies where appropriate (basically, the developer would still use the transitive dependency but at least it would be self-contained within the desired dependency such that version compatibility is managed at our layer),

The ipld crates [does](https://github.com/ipld/libipld/blob/master/src/lib.rs), it re-exports the transitive dependencies that are used for features. One downside to this is, if a developer another `cid` crate version, and they try and use that `cid::Cid` and the `libipld::Cid` Rust [would complain](https://doc.rust-lang.org/cargo/reference/resolver.html#version-incompatibility-hazards) that they aren't the same time.

I think this would also be the case if e.g. `dids` was both a direct, and a transitive dependency (i.e. if `credential` re-exported `dids` then `credentials::dids` types would be completely different from `dids` types.

**Comment by KendallWeihe** [comment]
Closing as we did this as "One crate" (to rule them all... and in the darkness, bind them) https://github.com/TBD54566975/web5-rs/pull/225

Thanks @diehuxx !
