### ISSUE TITLE
ffi bindings for crypto crate

### ISSUE THREAD

**Issue by amika-sq** [TBD54566975/web5-rs#27]
From the crypto crate, foreign languages will need to be able to do the following at the very least:
- [ ] Construct a `LocalKeyManager`
    * A concrete `KeyManager` is required to create a DID. Foreign languages will need to be able to instantiate one of these to provide as an argument to a DID constructor.
- [ ] Implement a `KeyStore` specific to their platform
    * One of our requirements for the Penguin deadline is to store keys in the Keychain on iOS. In order to do this, we'll need to expose the `KeyStore` trait to foreign languages so they can implement one.
- [ ] Serialize/deserialize private key to/from bytes
    * In order for a foreign language to be able to store a `PrivateKey` in the `KeyStore`, we'll need to expose serialize/deserialize functions on a `PrivateKey`

**Comment by KendallWeihe** [comment]
The initial scaffold for this is in place in this PR https://github.com/TBD54566975/web5-rs/pull/97

Will create more tickets for more detailed parts of this
