### ISSUE TITLE
ffi bindings for dids crate

### ISSUE THREAD

**Issue by amika-sq** [TBD54566975/web5-rs#29]
From the dids crate, foreign languages will need to be able to do the following at the very least:

* [ ] Create a `did:jwk`
* [ ] Sign content with a DID
* [ ] Verify content with a DID

Unknowns if needed in foreign languages:
* DID resolution
    * Does a foreign language need to resolve DID instance? Or should that logic live solely in the Rust code?
* Arbitrary DID uri resolution
    * Does a foreign language need to resolve arbitrary DIDs on their end? Or should that logic live solely in the Rust code?

**Comment by KendallWeihe** [comment]
The initial scaffold for this is in place in this PR https://github.com/TBD54566975/web5-rs/pull/97

Will create more tickets for more detailed parts of this
