### ISSUE TITLE
ffi bindings for credentials crate

### ISSUE THREAD

**Issue by amika-sq** [TBD54566975/web5-rs#30]
From the crypto crate, foreign languages will need to be able to do the following at the very least:

- [ ] Expose `PresentationDefinition` struct
    * Foreign languages will need to be able to inspect `PresentationDefinition` objects, as they are part of a tbDEX `Offering`. In order to do this, we must expose this type to foreign languages.

**Comment by KendallWeihe** [comment]
The initial scaffold for this is in place in this PR https://github.com/TBD54566975/web5-rs/pull/97

Will create more tickets for more detailed parts of this
