### ISSUE TITLE
Create singular ffi binding crate for all of `web5`

### ISSUE THREAD

**Issue by amika-sq** [TBD54566975/web5-rs#31]
We'll want to expose one singular SDK to Swift, instead of multiple disparate SDKs. Create a `web5-ffi` crate that can bundle all of the Rust dependencies into one, and create a `staticlib` for Swift to consume in a Swift Package/Cocoapod.

**Comment by KendallWeihe** [comment]
The initial scaffold for this is in place in this PR https://github.com/TBD54566975/web5-rs/pull/97

Will create more tickets for more detailed parts of this
