### ISSUE TITLE
Create Swift Package for web5 from ffi bindings

### ISSUE THREAD

**Issue by amika-sq** [TBD54566975/web5-rs#32]
Requires https://github.com/TBD54566975/web5-rs/issues/31 to be completed.

Once available, we'll want to consume the web5 ffi bindings, and package them all up into a Swift Package for consumption within the Swift language.

**Comment by KendallWeihe** [comment]
The initial scaffold for this is in place in this PR https://github.com/TBD54566975/web5-rs/pull/97/

Will create more tickets for more detailed parts of this
