### ISSUE TITLE
[Bug] rm: /tmp/web5-x86_64-apple-darwin

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/web5-rs#345]
When attempting to install Web5 CLI, the last line of the script prints an error message. Seems this is because this file was already moved in a previous step. So, I think it's safe to just remove the cleanup step in [install.sh](https://raw.githubusercontent.com/TBD54566975/web5-rs/main/crates/web5_cli/install.sh)

![image](https://github.com/user-attachments/assets/bdbbe5c4-e5e6-4415-8eca-e4cbbee47755)

**Comment by blackgirlbytes** [comment]
Actually going to close this and make this a new issue with more details, so Hacktoberfest participants can fix tis. Maybe with a title like Fix broken installation script for Web5 CLI
