### ISSUE TITLE
🐛 Bug: Fix Web5 CLI Installation Script

### ISSUE THREAD

**Issue by blackgirlbytes** [TBD54566975/web5-rs#384]
# 🐛 Bug: Fix Web5 CLI Installation Script

## 🔍 Problem Description

The current installation script for the Web5 CLI is encountering errors during execution. Users are experiencing issues that prevent successful installation.

## 🚫 Current Behavior

When running the installation command:

```bash
curl -L https://raw.githubusercontent.com/TBD54566975/web5-rs/main/crates/web5_cli/install.sh | bash -s v0.0.4
```

Users encounter an error message, preventing successful installation:

```
rm: /tmp/web5-aarch64-apple-darwin: No such file or directory
```

## ✅ Expected Behavior

The installation script should:
1. Correctly download and install the Web5 CLI.
2. Handle cleanup operations without errors.
3. Provide clear success or error messages to the user.

## 💡 Proposed Solution

1. Implement proper error handling and checks throughout the script.
2. Ensure the cleanup operation only attempts to remove files that exist.
3. Add verbose output to help users understand what's happening during the installation process.

## 🔄 Steps to Reproduce

1. Run the following command:
   ```bash
   curl -L https://raw.githubusercontent.com/TBD54566975/web5-rs/main/crates/web5_cli/install.sh | bash -s v0.0.4
   ```
2. Observe the error messages.

## ℹ️ Additional Information

- 🖥️ OS: macOS (as indicated by the Darwin reference in the error message)
- 🏗️ Architecture: ARM64 (based on the aarch64 filename in the error)
- 🏷️ Web5 CLI version: v0.0.4

## 🚀 Possible Improvements

1. Add a check to verify if the download was successful before attempting to move or chmod the file.
2. Implement a function to check and create the `/usr/local/bin` directory if it doesn't exist.
3. Use a trap to ensure cleanup of temporary files even if the script exits prematurely.
4. Add more informative error messages to help users troubleshoot installation issues.

**Comment by mushahidq** [comment]
Hi,

I'd like to work on this issue if someone else hasn't already taken this up

**Comment by blackgirlbytes** [comment]
yep you're assigned to it now.

**Comment by blackgirlbytes** [comment]
@mushahidq let us know how this is going for you or if you need any assistance!

**Comment by mushahidq** [comment]
Hi @blackgirlbytes. Thanks! I'm working on it. I'll post here if I need any help.
