### ISSUE TITLE
Implement our own `did:jwk` creation/resolution

### ISSUE THREAD

**Issue by amika-sq** [TBD54566975/web5-rs#41]
There was feedback in https://github.com/TBD54566975/web5-rs/pull/20 that we should be migrating towards our own implementation of `did:key`.

This task is to remove the Spruce's `did-jwk` depdendency from our `dids` crate, and implement it ourselves.

**Comment by KendallWeihe** [comment]
We're currently relying on the spruce crate and mapping to/from our types. This will remain in place until it becomes an apparent blocker.
