### ISSUE TITLE
Implement our own `did:key` creation/resolution

### ISSUE THREAD

**Issue by amika-sq** [TBD54566975/web5-rs#43]
Similar to #41 and #42. There's a desire to implement did methods in our codebases, and not rely on third-party libraries that implement the current specs. 

This task is to remove Spruce's `did-method-key` dependency (added in PR #25) from the `dids` crate and implement it ourselves.

**Comment by KendallWeihe** [comment]
We're currently relying on the spruce crate and mapping to/from our types. This will remain in place until it becomes an apparent blocker.

**Comment by KendallWeihe** [comment]
Reopening, will close once PR merged
